# Generated by Django 2.1.5 on 2019-06-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bot_lin_departamento',
            fields=[
                ('za_departamento', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_departamento', models.CharField(max_length=35)),
                ('abreviatura', models.CharField(max_length=12)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='bot_lin_pais',
            fields=[
                ('za_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=25)),
                ('abreviatura', models.CharField(max_length=12)),
                ('codigo_telefonico', models.CharField(max_length=10)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bot_lin_departamento',
            name='za_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.bot_lin_pais'),
        ),
    ]
